# Generated by Django 4.0.3 on 2022-03-21 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('age', models.FloatField(verbose_name='age')),
                ('gender', models.FloatField(verbose_name='gender')),
                ('height_cm', models.FloatField(verbose_name='height_cm')),
                ('weight_kg', models.FloatField(verbose_name='weight_kg')),
                ('fat', models.FloatField(verbose_name='fat')),
                ('diastolic', models.FloatField(verbose_name='diastolic')),
                ('systolic', models.FloatField(verbose_name='systolic')),
                ('gripForce', models.FloatField(verbose_name='gripForce')),
                ('sit_and_bend', models.FloatField(verbose_name='sit_and_bend')),
                ('situps', models.FloatField(verbose_name='situps')),
                ('jump_cm', models.FloatField(verbose_name='jump_cm')),
                ('body_class', models.FloatField(verbose_name='body_class')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
